### ISSUE TITLE
akordigu elŝuton de Reta Vortaro

### ISSUE THREAD

**Issue by wdiestel** [djuretic/praktika-vortaro-dicts#1]
La fonto-dosieroj de Revo ne plu aktualiĝas sub /tgz/, sed necesas ilin elŝuti el la ĉiutagaj eldonoj ĉe Github:
https://github.com/revuloj/revo-fonto/releases/latest

Kiel ekzemplon vi povas uzi [tiun elŝuto-skripton](https://github.com/revuloj/voko-araneo/blob/master/bin/revo_download_gh.sh).

**Comment by djuretic** [comment]
Mi finfine ĝistadigis la kodon, dankon @wdiestel
